export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";

export const APPLICATION_LOADING = "APPLICATION_LOADING";
export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const GET_APPLICATION = "GET_APPLICATION";
export const ADD_APPLICATION = "ADD_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";

export const APPLICATION_FORM_LOADING = "APPLICATION_FORM_LOADING";
export const GET_APPLICATION_FORMS = "GET_APPLICATION_FORMS";
export const GET_APPLICATION_FORM = "GET_APPLICATION_FORM";
export const ADD_APPLICATION_FORM = "ADD_APPLICATION_FORM";
export const DELETE_APPLICATION_FORM = "DELETE_APPLICATION_FORM";
